### ISSUE TITLE
Design a graph data type schema 

### ISSUE THREAD

**Issue by kevmo314** [muxable/stream-dashboard#19]
The schema to represent the underlying data in the graphs

lets create model in typescript'

**Comment by KeN095** [comment]
For a single/multi line chart:

{
modem: string
modem2: string (only if more than one modem is available)
bitrate: integer
streamTitle: string
startDate: Date()
endDate: Date()
}

Title of the graph will be the stream title
x-axis will have the times (time scale on x axis decided on startDate/endDate) while the y axis have bitrate numbers

i dont think stream title would be necessary as it could be scraped off of the user, but not sure

**Comment by KeN095** [comment]
We can also have a pie chart to represent uptime and down time per stream but the only schema i can think of would be

{
streamTitle: string
isLive: bool
}

**Comment by Leeoku** [comment]
I think that's good. Only thing I can think of to add is `framerate`, but for a mobile setup, things can greatly fluctuate. I think streamers will care more about having an active line, so can leave out for now

The only thing I can think of to improve is to consolidate the modems into an array. That way we don't hardcode the modems, we just throw them in and can access them as needed

**Comment by KeN095** [comment]
It seems kind of tricky but having `ping` might be better to show latency. For now we can leave both `packetLoss` and `ping` in.

**Comment by chungwwei** [comment]
We should also include `accountId`, `streamId`, and `timestamp`?

**Comment by Leeoku** [comment]
> 
> 
> We should also include `accountId`, `streamId`, and `timestamp`?

First two are good. Do we need timestamp? We already have dates

**Comment by KeN095** [comment]
Updated the schema. I'm not sure how often data is going to be passed in, but maybe timestamp can help in plotting. Not sure

**Comment by chungwwei** [comment]
`startDate` and `endDate` doesn't tell when the data point is registered thou. `timestamp` can do that and it can just be the x-value on the X-Axis.

with timestamp, we might be able to add this component.
![image](https://user-images.githubusercontent.com/39935368/135367681-baf170ca-95d0-4d87-93c5-14b738796844.png)

We also interested in the upstream/downstream bandwidth of each modem used.

`audio_bitrate` is also of interest for visualization

**Comment by Leeoku** [comment]
Good points @chungwwei . I agree timestamp would be useful, maybe another array of dates. I was so focused on calculating the timestamp value (like fetching current time when upload goes to 0, but completely forgot to assign it to a variable) 😓
